[container.image]
repository= "cafe-repo" # optional default is local
name="menu" # optional
tag="1.0.0"  # default is latest


[[cloud.config.files]]
    file="./menus/tea.json"
    mount_path="/home/ballerina/menus/tea.json"

[[cloud.config.files]]
    file="./menus/coffe.json"
    mount_path="/home/ballerina/menus/coffe.json"
