[container.image]
repository="anuruddhal" # Container repository to host the container
name="hello-api" # Name of the container image
tag="sample12" # Tag of the container

[[cloud.secret.files]]
file="./conf/data.txt" # External file path to mount as a secret volume
mount_path="/home/ballerina/data" # Path of the file within the container

[[cloud.secret.files]]
file="./conf/Config.toml" # External file path to mount as a secret volume
