[container.image]
repository="anuruddhal"
name="hello-api"
tag="sample5"

[[cloud.files]]
    file="./conf/data.txt"
    mount_path="/home/ballerina/data"
[[cloud.config.files]]
    file="./conf/Config.toml"
[[cloud.config.files]]
    file="./conf/Config2.toml"